### ISSUE TITLE
Only update changed attributes

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#22]
When updating a resource (POST <resource>/{id}), the Ruby library seems to (I don't speak Ruby) send only the properties that were actually updated (or skip the updated altogether if there were none). Should the Java library do this too?

**Comment by rjnienaber** [comment]
Yes, I think this behaviour should be in the java library as well.

**Comment by mmazi** [comment]
This will entail a bit more work as it is not a generally expected practice in Java SE. It will require either some kind of AOP and/or bytecode manipulation and reflection (introducing additional library dependencies), or verbosely manually wrapping all POJO setters with some code that records each update.

Discuss whether the budget and time frame permit this.

**Comment by rjnienaber** [comment]
What is the expected practise in Java SE? Are all properties sent back to the server regardless of whether they have changed or not?

**Comment by mmazi** [comment]
In terms of a HTTP API, only sending changed properties is of course desired functionality. I was referring to tracking changed POJO properties in general: unlike in Ruby, there are no facilities in Java SE to easily (transparently, with minimal overhead) do this. (Tracking changed properties is a more common practice in Java EE where some kind of AOP functionality is usually provided via libraries.)

The bottom line is that tracking change properties can be done, but at the cost of:
* additional 3rd-party dependencies, and
* bytecode manipulation might have to be used (either that, or manually adding code to all setters of all POJOs).

Both points might be an issue if we're targeting Android clients (among others) with our SDK. But if this turns out to be a problem, we can probably make updating only changed attributes optional in the SDK (so e.g. desktop clients can use it and Android clients can choose not to).

**Comment by mmazi** [comment]
See if this can be done in a simple way. An additional (possibly lightweight) dependency is preferable to a lot of boilerplate.

This is not just a convenience but may be required because the server may return an authorization failure (no permission) if some properties are attempted to be set, even if they are not changed (but double-check this; what would be an example?).
