### ISSUE TITLE
Provide some example client code

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#25]
Creating some example code / tutorial, like an implementation of [the Cookbook](https://connect.currencycloud.com/documentation/getting-started/cookbook), might be appropriate.

I already have the code, but need to decide on a good way to provide this. I see two options: 

1. A simple separate project, eg. currencycloud-java-example -- this would also showcase any necessary configuration (eg. maven dependencies),
2. A test class, eg. something like [DemoServerTest](https://github.com/CurrencyCloud/currencycloud-java/blob/master/src/test/java/com/currencycloud/client/http/DemoServerTest.java).

Solution 1. Is cleaner and more informative for beginners, with less clutter (like testing annotations), but is a bit harder to maintain (eg. SDK refactorings might break the example). 2. is simpler to maintain (automatically refactored when the SDK is refactored) and also provides some value to development as it can be used as a regression test.

**Comment by rjnienaber** [comment]
What about creating a top-level `examples` directory and putting a separate project in there? I would prefer to keep the example code together. This will just need to be excluded from the binary that is pushed to the maven repository.

**Comment by mmazi** [comment]
A separate top-level directory doesn't conform to Maven's project structure requirements.

I suggest we put the example code in the test sources directory (/src/test/java/), but keep it as a normal stand-alone java application (`public static void main`) as opposed to a test, and document it in the README/wiki. I think this gives us the benefits of both approaches mentioned above. All the code will be kept together, and the example code will not end up in the binaries (test code never does).

**Comment by rjnienaber** [comment]
:+1:
