### ISSUE TITLE
Create a PGP/GPG key that will be used to sign the final artifacts (jars) to be published

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#27]
Please read the [detailed instructions](http://central.sonatype.org/pages/working-with-pgp-signatures.html). This is a short summary of what needs to be done:

```bash
gpg --gen-key
gpg --list-keys
gpg2 --edit-key C6EED57A # delete subkeys if necessary -- please see the detailed instructions
> key 2
> delkey
gpg --keyserver hkp://pool.sks-keyservers.net --send-keys C6EED57A # replace with your keyid from --list-keys
```

This is only needed for final releases (we can publish snapshots unsigned).

The GPG key will be used to sign artifacts on a local machine (where the key is stored); I'll provide instructions to do this later. Eg., the GPG passphrase will need to be saved locally in Maven's ~/.m2/settings.xml.

**Comment by rjnienaber** [comment]
They key has been generated.
