### ISSUE TITLE
Register the project with Sonatype

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#28]
This is what needs to be done to publish the project artifacts (#21). The detailed instructions can be found at http://central.sonatype.org/pages/ossrh-guide.html#initial-setup .

This is required for both snapshot and final releases.

1. [Create a Sonatype Jira account](https://issues.sonatype.org/secure/Signup!default.jspa)
2. [Open a Jira issue](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134); provide the following details:
  * Summary: The official Java SDK for the Currency Cloud API
  * Group Id: com.currencycloud.currencycloud-java
  * Project URL: https://github.com/CurrencyCloud/currencycloud-java
  * SCM url: https://github.com/CurrencyCloud/currencycloud-java
  * Already Synced to Central: No

If "artifact id" is requested, the value is currencycloud-java. If PGP (public) keys are requested, see #27.

The account username and password will need to be encrypted and provided to Travis -- I'll provide instructions for this later.

**Comment by rjnienaber** [comment]
I've created the issue [OSSRH-1584](https://issues.sonatype.org/browse/OSSRH-15844)

**Comment by rjnienaber** [comment]
This has been [completed](https://issues.sonatype.org/browse/OSSRH-15844?focusedCommentId=317802&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-317802).
