### ISSUE TITLE
Push the snapshot artifacts to the Sonatype repo

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#34]
Sonatype credentials (the same as for their Jira) are required to push the artifacts to the Maven repository.

Please test that this works.

You need Java 7+ SDK, git and Maven 3 installed.

Add the credentials to `~/.m2/settings.xml`:

```xml
<settings>
  ...
  <servers>
    <server>
      <id>ossrh</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
  </servers>
  ...
</settings>
```

Then run this:

```sh
git clone git@github.com:CurrencyCloud/currencycloud-java.git
cd currencycloud-java
mvn clean deploy
```

**Comment by jeremy-cc** [comment]
Pushed to Sonatype Nexus:  0.7-SNAPSHOT

**Comment by jeremy-cc** [comment]
https://oss.sonatype.org/#nexus-search;quick~currencycloud-java

**Comment by jeremy-cc** [comment]
<dependency>
      <groupId>com.currencycloud.currencycloud-java</groupId>
      <artifactId>currencycloud-java</artifactId>
      <version>0.7-SNAPSHOT</version>
    </dependency>

**Comment by mmazi** [comment]
Great, thanks.
