### ISSUE TITLE
Provide encrypted credentials for Sonatype

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#35]
For Travis to push snapshot artifacts to the Sonaype maven repo automatcially (#30), it needs to know the CurrencyCloud's Sonatype credentials. Travis provides a way to supply these credentials in an encrypted form publicly (via the GitHub repo) so that only Travis can access them. Instructions how to do this follow. The easiest (described below) uses the Travis Ruby gem.

Please note that if the Sonatype password (or username) contains symbols with special meaning in shell scripting such as braces, parentheses, backslashes, and pipe symbols, these must be escaped as described [here](http://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols).

```sh
gem install travis  # use sudo if necessary
cd currencycloud-java  # the project code directory
travis encrypt CI_DEPLOY_USERNAME=<CurrencyCloud Sonatype username>
travis encrypt CI_DEPLOY_PASSWORD=<CurrencyCloud Sonatype password>
```

The last two commands will output something like `secure: ".... encrypted data ...."`. Please copy both of these values and paste them here.

**Comment by mmazi** [comment]
Wait, there may be a better alternative to securely provide credentials ([this](https://travis-ci.org/CurrencyCloud/currencycloud-java/settings/env_vars)). Let me study this a bit more.

**Comment by mmazi** [comment]
Let's go with [Travis Settings](https://travis-ci.org/CurrencyCloud/currencycloud-java/settings/env_vars). 

Please follow the above link and add two variables, `CI_DEPLOY_USERNAME` and `CI_DEPLOY_PASSWORD` with corresponding values. Do NOT turn on the "Display value in build logs" switch.

The variables will be stored in an encrypted form, won't be editable or visible in the Settings, and can only be accessed by Travis.

NOTE: The values can still potentially be exposed by manipulating the build process for this purpose by anyone with commit rights to the GitHub repository, but this cannot be avoided since the build process needs to have access to them.

**Comment by rjnienaber** [comment]
The variables have been added.
