### ISSUE TITLE
Typesafe enumerations

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#4]
There are many parameters/properties in the API that are declared as Strings, but can take a limited set of values (eg. country codes, currencies, custom statuses etc.). See if it makes sense to implement them as enums. Going with Strings for the time being.

**Comment by EAddario** [comment]
The use of the SDKs, although highly recommended,  is optional and some integrations use custom adaptors. For that reason we prefer to rely on the API itself to perform the validations and will not duplicate that logic in the SDKs
