### ISSUE TITLE
Payment creation missing payer country and address (for USD / CAD payments)

### ISSUE THREAD

**Issue by jonasmonese** [CurrencyCloud/currencycloud-java#40]
/*\* Create a Payment */
    @POST
    @Path("payments/create")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    Payment createPayment(
            @HeaderParam("X-Auth-Token") String authToken,
            @FormParam("currency") String currency,
            @FormParam("beneficiary_id") String beneficiaryId,
            @FormParam("amount") BigDecimal amount,
            @FormParam("reason") String reason,
            @FormParam("reference") String reference,
            @Nullable @FormParam("payment_date") java.sql.Date paymentDate,
            @Nullable @FormParam("payment_type") String paymentType,
            @Nullable @FormParam("conversion_id") String conversionId,
            @Nullable @FormParam("payer_entity_type") String payerEntityType,
            @Nullable @FormParam("payer_company_name") String payerCompanyName,
            @Nullable @FormParam("payer_first_name") String payerFirstName,
            @Nullable @FormParam("payer_last_name") String payerLastName,
            @Nullable @FormParam("payer_city") String payerCity,
            @Nullable @FormParam("payer_postcode") String payerPostcode,
            @Nullable @FormParam("payer_state_or_province") String payerStateOrProvince,
            @Nullable @FormParam("payer_date_of_birth") java.sql.Date payerDateOfBirth,
            @Nullable @FormParam("payer_country") String payerCountry,
            @Nullable @FormParam("payer_address[]") List<String> payerAddress,
            @Nullable @FormParam("payer_identification_type") String payerIdentificationType,
            @Nullable @FormParam("payer_identification_value") String payerIdentificationValue,
            @Nullable @FormParam("on_behalf_of") String onBehalfOf
    ) throws ResponseException;

public Payment createPayment(Payment payment, @Nullable Payer payer) throws CurrencyCloudException {
        if (payer == null) {
            payer = Payer.create();
        }
        return api.createPayment(authToken,
                                 payment.getCurrency(),
                                 payment.getBeneficiaryId(),
                                 payment.getAmount(),
                                 payment.getReason(),
                                 payment.getReference(),
                                 dateOnly(payment.getPaymentDate()),
                                 payment.getPaymentType(),
                                 payment.getConversionId(),
                                 payer.getLegalEntityType(),
                                 payer.getCompanyName(),
                                 payer.getFirstName(),
                                 payer.getLastName(),
                                 payer.getCity(),
                                 payer.getPostcode(),
                                 payer.getStateOrProvince(),
                                 dateOnly(payer.getDateOfBirth()),
                                 payer.getCountry(),
                                 payer.getAddress(),
                                 payer.getIdentificationType(),
                                 payer.getIdentificationValue(),
                                 onBehalfOf
        );
    }

**Comment by yorikim** [comment]
Work in progress

**Comment by EAddario** [comment]
See #39
