### ISSUE TITLE
Provide a more readable API

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#5]
Some of the method calls in the current Java API are a bit verbose and not easy to read; provide a better alternative.

Example of current API call:

        Beneficiary beneficiary = client.updateBeneficiary(
                "081596c9-02de-483e-9f2a-4cf55dcdf98c", "Test User 2",
                null, null, null, null, null, null, null, null, null,
                null, null, null, null, null, null, null,
                null, null, "Acme Inc.", null, null, "Manchester", 
                null, null, null, null, null, null
        );

A possible alternative:

        Beneficiary beneficiary = client.updateBeneficiary(
                new Beneficiary.Builder()
                        .Id("081596c9-02de-483e-9f2a-4cf55dcdf98c")
                        .BankAccountHolderName("Test User 2")
                        .BeneficiaryCompanyName("Acme Inc.")
                        .BeneficiaryCity("Manchester")
                        .build());

**Comment by rjnienaber** [comment]
I'm not sure if the builder pattern is much of an improvement over a POJO e.g.

```java
Beneficiary beneficiary = new Beneficiary();
beneficiary.id = "081596c9-02de-483e-9f2a-4cf55dcdf98c";
beneficiary.bankAccountHolderName = "Test User 2";
beneficiary.companyName = "Acme Inc.";
beneficiary.city = "Manchester";

Beneficiary updatedBeneficiary = client.updateBeneficiary(beneficiary);
```

**Comment by mmazi** [comment]
Agreed. The builder pattern adds a lot of verbose boilerplate code and doesn't help much since the beans are in general mutable anyway.

**Comment by mmazi** [comment]
Done where it makes sense (eg. the majority of API method parameters match properties of an existing POJO).

Still need to find a good way to do this for [Conversions](/CurrencyCloud/currencycloud-java/blob/master/src/main/java/com/currencycloud/client/CurrencyCloudClient.java#L351); keeping the non-pojo method signature for now.

**Comment by mmazi** [comment]
Done (Conversion wasn't problematic eventually).
