### ISSUE TITLE
Beneficiary Date of Birth

### ISSUE THREAD

**Issue by ghubdev** [CurrencyCloud/currencycloud-java#55]
The problem is related to create/update/validate beneficiary;
When I provide the beneficiary’s date of birth value I always have the following error:
“Invalid extra parameters:‘{:“beneficiary_date_of_birth\tdate”=>“1986-12-12"}’”

I think there is a bug in the sdk because in the CurrencyCloud.class the field beneficiaryDateOfBirth is binded with the value “beneficiary_date_of_birth date” where I think should be only “beneficiary_date_of_birth”.
The methods are : ” createBeneficiary(…), validateBeneficiary(…), updateBeneficiary(…)

**Comment by EAddario** [comment]
Thanks ghubdev. You are right, there's indeed a bug in the SDK and the extra **_date_** in the @FormParam("beneficiary_date_of_birth **_date_**") field for _createBeneficiary_, _validateBeneficiary_ and _updateBeneficiary_ needs to be the same as the corresponding field in _findBeneficiaries_.

We are preparing another release of the SDK, where among other things we are de-supporting Java 7. We will fix this issue in that version.

**Comment by EAddario** [comment]
Issue fixed in 1.0.3
